# Load / install packages needed for app ----------------------------------

require(plyr)

require(callr)
require(cowplot)
require(dashboardthemes)
require(data.table)
require(devtools)
require(dplyr) 
require(DT)
require(foreach)
require(ggforce)
require(ggnewscale)
require(ggplot2)
require(ggrepel)
require(Hmisc)
require(htmltools)
require(mada)
require(magic)
require(MASS)
require(patchwork)|
require(png)
require(R6)
require(readxl)
require(rio)
require(rlang)
require(rlist)
require(rstan)
require(scatterpie)
require(shiny)
require(shinyalert)
require(shinybusy)
require(shinydashboard)
require(shinyjs)
require(shinythemes)
require(shinyWidgets)
require(StanHeaders)
require(stringr)
require(tableHTML)
require(tidyverse)
require(usethis)
require(varhandle)

# Load functions ----------------------------------------------------------
source('./fn_general.R', local  = TRUE)
source('./fn_BVM.R', local  = TRUE)
source('./fn_SG.R', local  = TRUE)
source('./fn_LCM.R', local  = TRUE)

# Load modules ------------------------------------------------------------
source('./m_general.R', local  = TRUE)

source('./m_BVM_p1.R', local  = TRUE)
source('./m_BVM_p2.R', local  = TRUE)
source('./m_BVM_p3.R', local  = TRUE)
source('./m_BVM_p4.R', local  = TRUE)

source('./m_MR_p1_v3.R', local  = TRUE)
source('./m_MR_p2.R', local  = TRUE)
source('./m_MR_p3.R', local  = TRUE)
source('./m_MR_p4.R', local  = TRUE)

source('./m_SG_p1.R', local  = TRUE)
source('./m_SG_p2.R', local  = TRUE)
source('./m_SG_p3.R', local  = TRUE)
source('./m_SG_p4.R', local  = TRUE)

source('./m_LCM_p1_v2.R', local  = TRUE)
source('./m_LCM_p2.R', local  = TRUE)
source('./m_LCM_p3_v2.R', local  = TRUE)
source('./utils.R', local = TRUE)

# Load in images for TP, FP, FN, TN  -------------------------------------------------------------------
TPimg <-readPNG('./www/TP.png')
TNimg <-readPNG('./www/TN.png')
FPimg <-readPNG('./www/FP.png')
FNimg <-readPNG('./www/FN.png')